name = "the-button"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[vars]
TREASURY_ADDRESS = "SPKH9AWG0ENZ87J1X0PBD4HETP22G8W22AFNVF8K"
